global:
  datacenter: prod
  image: "hashicorp/consul:latest"
  imageK8S: "hashicorp/consul-k8s:latest"
# Expose the Consul UI through this LoadBalancer

ui:
  service:
    type: LoadBalancer
  enabled: true
# Allow Consul to inject the Connect proxy into Kubernetes containers
connectInject:
  enabled: true
  healthChecks:
    enabled: false
controller:
  enabled: true
meshGateway:
  enabled: true
client:
  enabled: true
  grpc: true


# Minimal Consul configuration. Not suitable for production.
server:
  replicas: 3
  bootstrapExpect: 3
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

# Sync Kubernetes and Consul services
syncCatalog:
  enabled: true
  default: true
  k8sAllowNamespaces: ['*']

